services:
  api:
    build:
      context: ./fastapi-backend
      dockerfile: Dockerfile

    image: backend-api
    container_name: kampung-merak-api

    env_file:
      - ./fastapi-backend/.env

    networks:
      - database
      - proxy

    restart: unless-stopped

networks:
  database:
    external: true
    name: webserver_database

  proxy:
    external: true
    name: webserver_proxy
